/**
 * Utility to generate WhatsApp sharing links for professional bakery invoices
 */

export const generateWhatsAppLink = (order) => {
  const phoneNumber = (order.phone || order.customer?.phone || '').replace(/\D/g, ''); // Clean phone number
  
  const total = Number(order.total || order.totalAmount || 0);
  const advance = Number(order.advance || 0);
  const balance = total - advance;
  const status = balance <= 0 ? '✅ FULLY PAID' : advance > 0 ? '🟡 PARTIALLY PAID' : '🔴 PAYMENT PENDING';

  const cName = typeof order.customer === 'object' ? (order.customer?.name || 'Valued Customer') : (order.customerName || order.customer || 'Valued Customer');

  // Branded Professional Template
  const message = `
*🧁 CREAM & CRUST — ARTISAN BAKERY*
*ORDER CONFIRMATION* 📜

*Order ID:* #${order.orderId?.split('-')[1] || order.orderId || '001'}
*Status:* ${status}
--------------------------------
👤 *Customer:* ${cName}
🎂 *Product:* ${order.product || 'Custom Bake'}
⚖️ *Weight:* ${order.size || order.cakeWeight || 'Standard'}
📅 *Delivery:* ${order.date || order.deliveryDate}
⏰ *Time:* ${order.time || order.deliveryTime || 'TBD'}

💰 *Financial Summary:*
*Total Amount:* ₹${total}
*Advance Paid:* ₹${advance}
*Balance Due:* ₹${balance}
--------------------------------
📍 *Delivery Address:*
${order.deliveryAddress || 'Pickup from Studio'}

${order.mapsLink ? `📍 *Location:* ${order.mapsLink}` : ''}

Thank you for choosing Cream & Crust! We are excited to bake for you. ✨
_Generated by Cream & Crust Bakery Manager_
  `.trim();

  const encodedMessage = encodeURIComponent(message);
  const fullPhone = phoneNumber.length === 10 ? '91' + phoneNumber : phoneNumber;
  return `https://wa.me/${fullPhone}?text=${encodedMessage}`;
};

export const shareToWhatsApp = (order) => {
  const link = generateWhatsAppLink(order);
  window.open(link, '_blank');
};
