/**
 * Utility to generate WhatsApp sharing links for professional bakery invoices.
 *
 * Uses dynamic business name from Firestore instead of hardcoded "Cream & Crust".
 */

import { openWhatsAppLink } from '../utils/openLink';
import { log } from '../utils/logger';

export const generateWhatsAppLink = (order, businessName = '') => {
  const phoneNumber = (order.phone || order.customer?.phone || '').replace(/\D/g, ''); // Clean phone number
  
  const total = Number(order.total || order.totalAmount || 0);
  const advance = Number(order.advance || 0);
  const balance = total - advance;
  const status = balance <= 0 ? '✅ FULLY PAID' : advance > 0 ? '🟡 PARTIALLY PAID' : '🔴 PAYMENT PENDING';

  const cName = typeof order.customer === 'object' ? (order.customer?.name || 'Valued Customer') : (order.customerName || order.customer || 'Valued Customer');

  // Use dynamic business name with fallback
  const bakeryName = businessName || 'Your Bakery';

  // Branded Professional Template
  const message = `
*🧁 ${bakeryName.toUpperCase()} — ARTISAN BAKERY*
*ORDER CONFIRMATION* 📜

*Order ID:* #${order.orderId?.split('-')[1] || order.orderId || '001'}
*Status:* ${status}
--------------------------------
👤 *Customer:* ${cName}
🎂 *Product:* ${order.product || 'Custom Bake'}
⚖️ *Weight:* ${order.size || order.cakeWeight || 'Standard'}
📅 *Delivery:* ${order.date || order.deliveryDate}
⏰ *Time:* ${order.time || order.deliveryTime || 'TBD'}

💰 *Financial Summary:*
*Total Amount:* ₹${total}
*Advance Paid:* ₹${advance}
*Balance Due:* ₹${balance}
--------------------------------
📍 *Delivery Address:*
${order.deliveryAddress || 'Pickup from Studio'}

${isSafeMapsLink(order.mapsLink) ? `📍 *Location:* ${order.mapsLink}` : ''}

Thank you for choosing ${bakeryName}! We are excited to bake for you. ✨
_Generated by ${bakeryName} — Bakery Manager_
  `.trim();

  const encodedMessage = encodeURIComponent(message);
  const fullPhone = phoneNumber.length === 10 ? '91' + phoneNumber : phoneNumber;
  return `https://wa.me/${fullPhone}?text=${encodedMessage}`;
};

/** Only allow verified Google Maps HTTPS URLs to prevent link injection. */
function isSafeMapsLink(url) {
  if (!url || typeof url !== 'string') return false;
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== 'https:') return false;
    const allowed = ['maps.google.com', 'maps.app.goo.gl', 'goo.gl', 'www.google.com'];
    return allowed.some(host => parsed.hostname === host || parsed.hostname.endsWith('.' + host));
  } catch {
    return false;
  }
}

export const shareToWhatsApp = async (order, businessName = '') => {
  const link = generateWhatsAppLink(order, businessName);
  log.whatsapp('shareToWhatsApp: opening link for order', order.orderId || order.id);
  await openWhatsAppLink(link);
};
