/**
 * Utility to generate WhatsApp sharing links for invoices
 */

export const generateWhatsAppLink = (order) => {
  const phoneNumber = order.phone?.replace(/\D/g, '') || ''; // Clean phone number
  
  // Branded Professional Template
  const message = `
*🧁 CREAM & CRUST — BAKERY*
*Order Confirmation* 📜

*Order ID:* #${order.orderId?.split('-')[1] || order.orderId || '001'}
--------------------------------
👤 *Customer:* ${order.customer}
🎂 *Product:* ${order.product}
⚖️ *Weight:* ${order.size || 'N/A'}
📅 *Delivery:* ${order.date}
⏰ *Time:* ${order.time || 'TBD'}

💰 *Payment Details:*
*Total:* ₹${order.total}
*Advance:* ₹${order.advance}
*Balance:* ₹${order.total - order.advance}

📍 *Address:* ${order.deliveryAddress || 'N/A'}
${order.mapsLink ? `*Maps:* ${order.mapsLink}` : ''}
--------------------------------
Thank you for making us part of your celebrations! ✨
_Generated by Cream & Crust Bakery Manager_
  `.trim();

  const encodedMessage = encodeURIComponent(message);
  const fullPhone = phoneNumber.length === 10 ? '91' + phoneNumber : phoneNumber;
  return `https://wa.me/${fullPhone}?text=${encodedMessage}`;
};

export const shareToWhatsApp = (order) => {
  const link = generateWhatsAppLink(order);
  window.open(link, '_blank');
};
