import React, { useState, useEffect, useMemo } from 'react';
import { Plus, Trash2, X, ShoppingCart, Share2, CheckCircle2, Circle, Loader2, Info, ChevronRight, Sparkles, Receipt, RefreshCcw, Tag } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { subscribeToShoppingList, addShoppingItemToDB, toggleShoppingItemInDB, deleteShoppingItemFromDB, subscribeToInventory, addExpenseToDB } from '../services/db';
import { useAuth } from '../context/AuthContext';
import { showToast, triggerHaptic } from '../components/iOS';

const UNITS = ['pcs', 'kg', 'g', 'L', 'ml', 'cups', 'tbsp', 'tsp', 'dozen', 'packets'];
const CATEGORIES = ['Dairy', 'Dry Goods', 'Packaging', 'Vegetables', 'Fruits', 'Spices', 'Decorations', 'Other'];

const emptyForm = { name: '', qty: '', unit: 'kg', category: 'Dry Goods' };

export default function ShoppingList() {
  const [items, setItems]           = useState([]);
  const [inventory, setInventory]   = useState([]);
  const [loading, setLoading]       = useState(true);
  const [showModal, setShowModal]   = useState(false);
  const [showPrompt, setShowPrompt] = useState(null); // Item to prompt for expense conversion
  const [form, setForm]             = useState(emptyForm);
  const [submitting, setSubmitting] = useState(false);
  const { currentUser } = useAuth();

  useEffect(() => {
    if (!currentUser) return;
    const unsubItems = subscribeToShoppingList(
      (data) => { setItems(data); setLoading(false); },
      ()     => setLoading(false),
      currentUser.uid
    );
    const unsubInv = subscribeToInventory(
      (data) => setInventory(data),
      null,
      currentUser.uid
    );
    return () => { unsubItems(); unsubInv(); };
  }, [currentUser]);

  const pending = items.filter(i => !i.bought);
  const bought  = items.filter(i => i.bought);

  const lowStockCount = useMemo(() => {
    return inventory.filter(i => Number(i.stock) <= Number(i.minStock || 0)).length;
  }, [inventory]);

  const handleAdd = async (ev) => {
    ev.preventDefault();
    if (!form.name) return showToast('Enter item name', 'error');
    setSubmitting(true);
    triggerHaptic('medium');
    try {
      await addShoppingItemToDB({ 
        ...form,
        userId: currentUser.uid,
        createdAt: new Date().toISOString()
      });
      showToast('Item added!', 'success');
      setForm(emptyForm);
      setShowModal(false);
      triggerHaptic('success');
    } catch {
      showToast('Failed to add item', 'error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleToggle = async (item) => {
    try {
      const newStatus = !item.bought;
      await toggleShoppingItemInDB(item.id, newStatus);
      triggerHaptic(newStatus ? 'success' : 'light');
      
      // If marked as bought, prompt for expense conversion
      if (newStatus) {
        setShowPrompt(item);
      }
    } catch {
      showToast('Failed to update', 'error');
    }
  };

  const handleConvertToExpense = async (item, amount) => {
    if (!amount) return showToast('Enter amount paid', 'error');
    try {
      await addExpenseToDB({
        description: `${item.name} (${item.qty}${item.unit})`,
        amount: Number(amount),
        category: item.category === 'Packaging' ? 'Packaging' : 'Ingredients',
        date: new Date().toISOString().split('T')[0],
        userId: currentUser.uid
      });
      showToast('Added to Expenses! 💸', 'success');
      setShowPrompt(null);
    } catch {
      showToast('Failed to add expense', 'error');
    }
  };

  const syncFromInventory = async () => {
    const lowStock = inventory.filter(i => Number(i.stock) <= Number(i.minStock || 0));
    if (lowStock.length === 0) return showToast('Inventory is healthy! ✨', 'info');
    
    triggerHaptic('medium');
    let added = 0;
    for (const invItem of lowStock) {
      // Check if already in shopping list
      if (!items.some(i => i.name.toLowerCase() === invItem.name.toLowerCase() && !i.bought)) {
        await addShoppingItemToDB({
          name: invItem.name,
          qty: (Number(invItem.minStock || 0) * 2) - Number(invItem.stock),
          unit: invItem.unit || 'kg',
          category: invItem.category || 'Dry Goods',
          userId: currentUser.uid
        });
        added++;
      }
    }
    showToast(added > 0 ? `Added ${added} items from Inventory` : 'Items already in list', 'success');
  };

  const handleShareWhatsApp = () => {
    if (pending.length === 0) return showToast('No items to share', 'error');
    const text = `🛒 *Shopping List — Cream & Crust*\n\n${pending.map(i => `• ${i.name}${i.qty ? ` (${i.qty} ${i.unit})` : ''}`).join('\n')}\n\n_Generated by Cream & Crust App_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const ItemRow = ({ item }) => (
    <motion.div
      layout
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.9 }}
      style={{
        display: 'flex', alignItems: 'center', gap: 16,
        padding: '16px 20px', borderBottom: '1px solid var(--border)',
        background: item.bought ? 'rgba(0,0,0,0.02)' : 'var(--card)',
        transition: 'all 0.3s'
      }}
    >
      <motion.button
        whileTap={{ scale: 0.8 }}
        onClick={() => handleToggle(item)}
        style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, color: item.bought ? '#34C759' : 'var(--text3)', flexShrink: 0 }}
      >
        {item.bought ? <CheckCircle2 size={26} strokeWidth={2.5} /> : <Circle size={26} strokeWidth={2} />}
      </motion.button>

      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontWeight: 700, fontSize: '1.05rem',
          textDecoration: item.bought ? 'line-through' : 'none',
          color: item.bought ? 'var(--text3)' : 'var(--text)',
          transition: 'all 0.3s'
        }}>
          {item.name}
        </div>
        {item.qty && (
          <div style={{ fontSize: 13, color: 'var(--text3)', marginTop: 4, display: 'flex', alignItems: 'center', gap: 4 }}>
            <Tag size={12} /> {item.qty} {item.unit}
          </div>
        )}
      </div>

      <div style={{ display: 'flex', gap: 8 }}>
        {item.bought && (
          <button
            onClick={() => setShowPrompt(item)}
            style={{ color: 'var(--accent)', background: 'var(--cream)', padding: '6px 10px', borderRadius: 10, fontSize: 12, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4 }}
          >
            <Receipt size={14} /> Record Cost
          </button>
        )}
        <button
          className="btn-icon"
          onClick={() => deleteShoppingItemFromDB(item.id)}
          style={{ color: 'rgba(255, 59, 48, 0.6)', width: 32, height: 32, background: 'none' }}
        >
          <Trash2 size={16} />
        </button>
      </div>
    </motion.div>
  );

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="fade-in">
      {/* Header */}
      <div className="page-header" style={{ marginBottom: 32 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 16 }}>
          <div>
            <h1 style={{ fontSize: '2.4rem', fontWeight: 800, letterSpacing: '-0.04em' }}>Shopping List</h1>
            <p style={{ color: 'var(--text2)', fontSize: '1rem' }}>Restock your supplies efficiently</p>
          </div>
          <div style={{ display: 'flex', gap: 12 }}>
            <button className="btn btn-outline" onClick={handleShareWhatsApp} style={{ borderRadius: 14, color: '#25D366', borderColor: '#25D366' }}>
              <Share2 size={18} /> Share
            </button>
            <button className="btn btn-primary" onClick={() => setShowModal(true)} style={{ borderRadius: 14, padding: '12px 24px' }}>
              <Plus size={20} /> Add Item
            </button>
          </div>
        </div>
      </div>

      {/* Action Cards */}
      <div className="content-grid" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16, marginBottom: 32 }}>
        <div className="card" style={{ display: 'flex', alignItems: 'center', gap: 20, padding: '24px' }}>
          <div style={{ width: 54, height: 54, borderRadius: 16, background: 'rgba(52, 199, 89, 0.1)', color: '#34C759', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <ShoppingCart size={28} />
          </div>
          <div>
            <div className="stat-label">To Buy</div>
            <div style={{ fontSize: '1.8rem', fontWeight: 800 }}>{pending.length} <span style={{ fontSize: '0.9rem', color: 'var(--text3)', fontWeight: 600 }}>items</span></div>
          </div>
        </div>

        <motion.div 
          whileTap={{ scale: 0.98 }}
          onClick={syncFromInventory}
          className="card" 
          style={{ 
            display: 'flex', alignItems: 'center', gap: 20, padding: '24px', 
            cursor: 'pointer', border: lowStockCount > 0 ? '1.5px solid var(--accent)' : '1px solid var(--border)',
            background: lowStockCount > 0 ? 'linear-gradient(135deg, var(--bg2), var(--cream))' : 'var(--bg2)'
          }}
        >
          <div style={{ width: 54, height: 54, borderRadius: 16, background: lowStockCount > 0 ? 'rgba(212, 113, 74, 0.1)' : 'rgba(0,0,0,0.05)', color: lowStockCount > 0 ? 'var(--accent)' : 'var(--text3)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <RefreshCcw size={28} className={lowStockCount > 0 ? 'animate-spin-slow' : ''} />
          </div>
          <div style={{ flex: 1 }}>
            <div className="stat-label">Smart Sync</div>
            <div style={{ fontSize: '1.1rem', fontWeight: 800, color: lowStockCount > 0 ? 'var(--accent)' : 'var(--text)' }}>
              {lowStockCount > 0 ? `${lowStockCount} items low stock` : 'Inventory Healthy'}
            </div>
          </div>
          <ChevronRight size={20} color="var(--text3)" />
        </motion.div>
      </div>

      {/* Main List Area */}
      {loading ? (
        <div style={{ padding: 100, textAlign: 'center' }}>
          <Loader2 className="animate-spin" size={40} color="var(--accent)" />
        </div>
      ) : items.length === 0 ? (
        <div className="card" style={{ padding: 80, textAlign: 'center' }}>
          <div style={{ fontSize: '5rem', marginBottom: 24 }}>🛒</div>
          <h2 style={{ fontSize: '1.8rem', fontWeight: 800 }}>List is empty</h2>
          <p style={{ color: 'var(--text3)', maxWidth: 350, margin: '12px auto 32px' }}>Everything looks stocked up! Or maybe it's time to plan your next market trip?</p>
          <button className="btn btn-primary" onClick={() => setShowModal(true)} style={{ padding: '14px 32px', borderRadius: 16 }}>
            <Plus size={20} /> Add Your First Item
          </button>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
          {/* Pending Section */}
          {pending.length > 0 && (
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16, padding: '0 8px' }}>
                <Sparkles size={18} color="var(--accent)" />
                <h3 style={{ fontSize: '1.1rem', fontWeight: 800 }}>Need to Buy</h3>
                <span className="badge confirmed" style={{ padding: '2px 10px' }}>{pending.length}</span>
              </div>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                {CATEGORIES.map(cat => {
                  const catItems = pending.filter(i => (i.category || 'Other') === cat);
                  if (catItems.length === 0) return null;
                  return (
                    <div key={cat} className="card" style={{ padding: 0, overflow: 'hidden', border: 'none', boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                      <div style={{ padding: '14px 20px', background: 'rgba(0,0,0,0.02)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border)' }}>
                        <span style={{ fontSize: 12, fontWeight: 800, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>{cat}</span>
                      </div>
                      <AnimatePresence mode="popLayout">
                        {catItems.map(item => <ItemRow key={item.id} item={item} />)}
                      </AnimatePresence>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Bought Section */}
          {bought.length > 0 && (
            <div style={{ opacity: 0.8 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, padding: '0 8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <CheckCircle2 size={18} color="#34C759" />
                  <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: 'var(--text2)' }}>Recently Bought</h3>
                </div>
                <button
                  onClick={async () => { if (window.confirm('Clear all bought items?')) bought.forEach(i => deleteShoppingItemFromDB(i.id)); }}
                  style={{ fontSize: 13, color: '#FF3B30', fontWeight: 700 }}
                >
                  Clear all
                </button>
              </div>
              <div className="card" style={{ padding: 0, overflow: 'hidden', border: '1px solid var(--border)', background: 'transparent', boxShadow: 'none' }}>
                <AnimatePresence mode="popLayout">
                  {bought.map(item => <ItemRow key={item.id} item={item} />)}
                </AnimatePresence>
              </div>
            </div>
          )}
        </div>
      )}

      <AnimatePresence>
        {showModal && (
          <div className="modal-overlay" onClick={() => setShowModal(false)}>
            <motion.div
              initial={{ y: '100%', opacity: 0 }} 
              animate={{ y: 0, opacity: 1 }} 
              exit={{ y: '100%', opacity: 0 }}
              transition={{ type: 'spring', damping: 30, stiffness: 350 }}
              className="modal" 
              onClick={e => e.stopPropagation()} 
              style={{ maxWidth: 480, padding: 0, borderRadius: 28, overflow: 'hidden' }}
            >
              <div style={{ padding: '32px 32px 24px', background: 'linear-gradient(135deg, var(--bg2), var(--cream))', borderBottom: '1px solid var(--border)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <h2 style={{ margin: 0, fontSize: '1.6rem', fontWeight: 900, letterSpacing: '-0.04em' }}>Add Item</h2>
                    <p style={{ color: 'var(--text3)', fontSize: '0.9rem', marginTop: 4 }}>What are we missing today?</p>
                  </div>
                  <button className="btn-icon" onClick={() => setShowModal(false)} style={{ background: 'rgba(0,0,0,0.05)', borderRadius: '50%' }}><X size={20} /></button>
                </div>
              </div>

              <form onSubmit={handleAdd} style={{ padding: 32 }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
                  <div className="form-group">
                    <label className="form-label">Item Name</label>
                    <input required autoFocus placeholder="e.g. Premium Butter" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} style={{ height: 56, borderRadius: 16, background: 'var(--bg)', border: '1px solid var(--border)', fontSize: '1.1rem', fontWeight: 600 }} />
                  </div>

                  <div className="form-group">
                    <label className="form-label">Category</label>
                    <div style={{ display: 'flex', gap: 8, overflowX: 'auto', paddingBottom: 4 }} className="no-scrollbar">
                      {CATEGORIES.map(c => (
                        <button
                          key={c}
                          type="button"
                          onClick={() => setForm({ ...form, category: c })}
                          style={{
                            padding: '10px 18px', borderRadius: 12, fontSize: 13, fontWeight: 700, whiteSpace: 'nowrap',
                            background: form.category === c ? 'var(--text)' : 'var(--bg)',
                            color: form.category === c ? 'white' : 'var(--text2)',
                            border: 'none', cursor: 'pointer', transition: 'all 0.2s'
                          }}
                        >
                          {c}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                    <div className="form-group">
                      <label className="form-label">Quantity</label>
                      <input type="number" min="0" step="0.1" placeholder="5" value={form.qty} onChange={e => setForm({ ...form, qty: e.target.value })} style={{ height: 50, borderRadius: 14, background: 'var(--bg)', border: '1px solid var(--border)', textAlign: 'center', fontWeight: 800 }} />
                    </div>
                    <div className="form-group">
                      <label className="form-label">Unit</label>
                      <select value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })} style={{ height: 50, borderRadius: 14, background: 'var(--bg)', border: '1px solid var(--border)' }}>
                        {UNITS.map(u => <option key={u}>{u}</option>)}
                      </select>
                    </div>
                  </div>

                  <div className="form-group">
                    <label className="form-label">Priority</label>
                    <div style={{ display: 'flex', gap: 10 }}>
                      {[
                        { label: 'Low', color: '#34C759' },
                        { label: 'Medium', color: '#FF9500' },
                        { label: 'Urgent', color: '#FF3B30' }
                      ].map(p => (
                        <button
                          key={p.label}
                          type="button"
                          onClick={() => setForm({ ...form, priority: p.label })}
                          style={{
                            flex: 1, padding: '12px 0', borderRadius: 14, fontSize: 13, fontWeight: 800,
                            border: form.priority === p.label ? `2px solid ${p.color}` : '1px solid var(--border)',
                            background: form.priority === p.label ? `${p.color}15` : 'white',
                            color: form.priority === p.label ? p.color : 'var(--text3)',
                            transition: 'all 0.2s'
                          }}
                        >
                          {p.label}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                <div style={{ marginTop: 32 }}>
                  <button type="submit" className="btn btn-primary" style={{ width: '100%', height: 60, borderRadius: 20, fontSize: '1.1rem', fontWeight: 800, boxShadow: 'var(--shadow-accent)' }} disabled={submitting}>
                    {submitting ? <Loader2 className="animate-spin" /> : '+ Add to Shopping List'}
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Expense Conversion Prompt */}
      <AnimatePresence>
        {showPrompt && (
          <div className="modal-overlay" style={{ zIndex: 300 }} onClick={() => setShowPrompt(null)}>
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }}
              className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: 400, textAlign: 'center', padding: 32 }}
            >
              <div style={{ width: 64, height: 64, borderRadius: '50%', background: 'rgba(212, 113, 74, 0.1)', color: 'var(--accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px' }}>
                <Receipt size={32} />
              </div>
              <h2 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: 8 }}>Record Expense?</h2>
              <p style={{ color: 'var(--text3)', fontSize: '0.95rem', marginBottom: 24 }}>
                Would you like to record <strong>{showPrompt.name}</strong> as an expense in your accounts?
              </p>
              
              <div style={{ marginBottom: 24 }}>
                <div style={{ position: 'relative' }}>
                  <span style={{ position: 'absolute', left: 14, top: 14, fontWeight: 700, color: 'var(--text)' }}>₹</span>
                  <input 
                    type="number" 
                    id="expense-amt" 
                    autoFocus 
                    placeholder="Amount paid" 
                    style={{ paddingLeft: 30, height: 48, borderRadius: 12, textAlign: 'center', fontWeight: 800, fontSize: '1.2rem' }} 
                  />
                </div>
              </div>

              <div style={{ display: 'flex', gap: 12 }}>
                <button 
                  className="btn btn-primary" 
                  style={{ flex: 1, height: 48, borderRadius: 12 }}
                  onClick={() => handleConvertToExpense(showPrompt, document.getElementById('expense-amt').value)}
                >
                  Yes, Save Expense
                </button>
                <button 
                  className="btn btn-outline" 
                  style={{ flex: 1, height: 48, borderRadius: 12 }}
                  onClick={() => setShowPrompt(null)}
                >
                  No, Just Bought
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

